# Este archivo define todas los tipos de usuarios, 
# y las reglas o condiciones de proporciones de tipos de documentos/ventanas
# que se deben cumplir para cada uno, ademas de definir los delimitadores o separadores
# de palabras y el umbral de ocurrencias para que un tipo de documento/ventana cuente
# al momento de determinar el tipo de usario

DELIMITADORES " ,./|:;'\t"
UMBRAL_OCURRENCIAS 3

USUARIO Personal_Administrativo
CONDICION CORREO 0.90
FIN_USUARIO

USUARIO Personal_Tecnico
CONDICION CORREO 0.40
CONDICION REPORTE 0.40
FIN_USUARIO

USUARIO Profesor
CONDICION CORREO 0.40
CONDICION ARTICULO 0.40
FIN_USUARIO

USUARIO Estudiante
CONDICION ARTICULO 0.40
CONDICION REPORTE 0.40
FIN_USUARIO